allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  'brace-expansion@1.1.18': 1.1.21
  'brace-expansion@5.0.9': 5.0.12
  dompurify: 3.4.16
  fast-copy: 3.1.0
  nodemailer: 10.0.15
  source-map-js: 1.2.2
  undici: 7.29.1
patchedDependencies:
  '@payloadcms/ui@3.90.2': patches/@payloadcms__ui@3.90.2.patch
