import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."fr" AS ENUM('none', 'outline');
  ALTER TABLE "pages_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "pages_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "pages_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "pages_blocks_listing" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "pages_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "pages_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "pages_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "pages_blocks_documents" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "pages_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "pages_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "pages_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "pages_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "pages_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "pages_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "pages_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "pages_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "pages_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "pages_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "pages_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "pages_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_pages_v_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_pages_v_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_pages_v_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_pages_v_blocks_listing" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_pages_v_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_pages_v_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_pages_v_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_pages_v_blocks_documents" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_pages_v_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_pages_v_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_pages_v_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_pages_v_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_pages_v_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_pages_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_pages_v_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_pages_v_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_pages_v_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_pages_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_pages_v_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_pages_v_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "posts_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "posts_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "posts_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "posts_blocks_listing" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "posts_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "posts_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "posts_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "posts_blocks_documents" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "posts_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "posts_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "posts_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "posts_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "posts_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "posts_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "posts_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "posts_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "posts_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "posts_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "posts_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "posts_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_posts_v_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_posts_v_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_posts_v_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_posts_v_blocks_listing" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_posts_v_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_posts_v_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_posts_v_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_posts_v_blocks_documents" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_posts_v_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_posts_v_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_posts_v_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_posts_v_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_posts_v_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_posts_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_posts_v_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_posts_v_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_posts_v_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_posts_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_posts_v_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_posts_v_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "events_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "events_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "events_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "events_blocks_listing" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "events_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "events_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "events_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "events_blocks_documents" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "events_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "events_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "events_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "events_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "events_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "events_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "events_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "events_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "events_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "events_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "events_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "events_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_events_v_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_events_v_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_events_v_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_events_v_blocks_listing" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_events_v_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_events_v_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_events_v_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_events_v_blocks_documents" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_events_v_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_events_v_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_events_v_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_events_v_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_events_v_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_events_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_events_v_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_events_v_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_events_v_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_events_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_events_v_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_events_v_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "event_cycles_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "event_cycles_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "event_cycles_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "event_cycles_blocks_listing" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "event_cycles_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "event_cycles_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "event_cycles_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "event_cycles_blocks_documents" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "event_cycles_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "event_cycles_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "event_cycles_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "event_cycles_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "event_cycles_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "event_cycles_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "event_cycles_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "event_cycles_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "event_cycles_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "event_cycles_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "event_cycles_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "event_cycles_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_listing" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_documents" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_event_cycles_v_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "partners_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "partners_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "partners_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "partners_blocks_listing" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "partners_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "partners_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "partners_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "partners_blocks_documents" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "partners_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "partners_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "partners_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "partners_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "partners_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "partners_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "partners_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "partners_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "partners_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "partners_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "partners_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "partners_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_partners_v_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_partners_v_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_partners_v_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_partners_v_blocks_listing" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_partners_v_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_partners_v_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_partners_v_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_partners_v_blocks_documents" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_partners_v_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_partners_v_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_partners_v_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_partners_v_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_partners_v_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_partners_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_partners_v_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_partners_v_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_partners_v_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_partners_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";
  ALTER TABLE "_partners_v_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE "public"."fr" USING (CASE WHEN "frame" THEN 'outline' ELSE 'none' END)::"public"."fr";
  ALTER TABLE "_partners_v_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT 'none'::"public"."fr";`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "pages_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "pages_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "pages_blocks_listing" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "pages_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "pages_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "pages_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "pages_blocks_documents" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "pages_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "pages_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "pages_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "pages_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "pages_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "pages_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "pages_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "pages_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "pages_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "pages_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "pages_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "pages_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "pages_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_pages_v_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_pages_v_blocks_listing" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_pages_v_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_pages_v_blocks_documents" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_pages_v_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_pages_v_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_pages_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_pages_v_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_pages_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_pages_v_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "posts_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "posts_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "posts_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "posts_blocks_listing" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "posts_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "posts_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "posts_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "posts_blocks_documents" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "posts_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "posts_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "posts_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "posts_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "posts_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "posts_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "posts_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "posts_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "posts_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "posts_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "posts_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "posts_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "posts_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_posts_v_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_posts_v_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_posts_v_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_posts_v_blocks_listing" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_posts_v_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_posts_v_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_posts_v_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_posts_v_blocks_documents" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_posts_v_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_posts_v_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_posts_v_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_posts_v_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_posts_v_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_posts_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_posts_v_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_posts_v_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_posts_v_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_posts_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_posts_v_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_posts_v_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "events_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "events_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "events_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "events_blocks_listing" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "events_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "events_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "events_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "events_blocks_documents" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "events_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "events_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "events_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "events_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "events_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "events_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "events_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "events_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "events_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "events_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "events_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "events_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "events_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_events_v_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_events_v_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_events_v_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_events_v_blocks_listing" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_events_v_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_events_v_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_events_v_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_events_v_blocks_documents" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_events_v_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_events_v_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_events_v_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_events_v_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_events_v_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_events_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_events_v_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_events_v_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_events_v_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_events_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_events_v_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_events_v_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_events_v_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "event_cycles_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "event_cycles_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "event_cycles_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "event_cycles_blocks_listing" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "event_cycles_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "event_cycles_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "event_cycles_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "event_cycles_blocks_documents" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "event_cycles_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "event_cycles_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "event_cycles_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "event_cycles_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "event_cycles_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "event_cycles_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "event_cycles_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "event_cycles_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "event_cycles_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "event_cycles_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "event_cycles_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "event_cycles_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "event_cycles_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_event_cycles_v_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_event_cycles_v_blocks_listing" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_event_cycles_v_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_event_cycles_v_blocks_documents" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_event_cycles_v_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_event_cycles_v_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_event_cycles_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_event_cycles_v_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_event_cycles_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_event_cycles_v_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_event_cycles_v_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "partners_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "partners_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "partners_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "partners_blocks_listing" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "partners_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "partners_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "partners_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "partners_blocks_documents" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "partners_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "partners_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "partners_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "partners_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "partners_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "partners_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "partners_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "partners_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "partners_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "partners_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "partners_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "partners_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "partners_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_partners_v_blocks_rich_text" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_rich_text" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_partners_v_blocks_rich_text" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_partners_v_blocks_listing" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_listing" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_partners_v_blocks_listing" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_partners_v_blocks_media_gallery" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_media_gallery" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_partners_v_blocks_media_gallery" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_partners_v_blocks_documents" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_documents" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_partners_v_blocks_documents" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_partners_v_blocks_attachments" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_attachments" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_partners_v_blocks_attachments" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_partners_v_blocks_member_profiles" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_member_profiles" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_partners_v_blocks_member_profiles" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_partners_v_blocks_column_layout_columns" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_partners_v_blocks_column_layout_columns" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_partners_v_blocks_column_layout" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_column_layout" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_partners_v_blocks_column_layout" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_partners_v_blocks_section_group_sections" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_partners_v_blocks_section_group_sections" ALTER COLUMN "frame" SET DEFAULT false;
  ALTER TABLE "_partners_v_blocks_section_group" ALTER COLUMN "frame" DROP DEFAULT;
  ALTER TABLE "_partners_v_blocks_section_group" ALTER COLUMN "frame" SET DATA TYPE boolean USING ("frame" = 'outline');
  ALTER TABLE "_partners_v_blocks_section_group" ALTER COLUMN "frame" SET DEFAULT false;
  DROP TYPE "public"."fr";`)
}
