import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_heading_heading_level" AS ENUM('h2', 'h3', 'h4');
  CREATE TYPE "public"."enum__pages_v_blocks_heading_heading_level" AS ENUM('h2', 'h3', 'h4');
  CREATE TYPE "public"."enum_posts_blocks_heading_heading_level" AS ENUM('h2', 'h3', 'h4');
  CREATE TYPE "public"."enum__posts_v_blocks_heading_heading_level" AS ENUM('h2', 'h3', 'h4');
  CREATE TYPE "public"."enum_events_blocks_heading_heading_level" AS ENUM('h2', 'h3', 'h4');
  CREATE TYPE "public"."enum__events_v_blocks_heading_heading_level" AS ENUM('h2', 'h3', 'h4');
  CREATE TYPE "public"."enum_event_cycles_blocks_heading_heading_level" AS ENUM('h2', 'h3', 'h4');
  CREATE TYPE "public"."enum__event_cycles_v_blocks_heading_heading_level" AS ENUM('h2', 'h3', 'h4');
  CREATE TYPE "public"."enum_partners_blocks_heading_heading_level" AS ENUM('h2', 'h3', 'h4');
  CREATE TYPE "public"."enum__partners_v_blocks_heading_heading_level" AS ENUM('h2', 'h3', 'h4');
  CREATE TYPE "public"."enum_footer_columns_alignment" AS ENUM('left', 'center', 'right');
  ALTER TABLE "pages_blocks_heading" ADD COLUMN "heading_level" "enum_pages_blocks_heading_heading_level" DEFAULT 'h2';
  ALTER TABLE "pages_blocks_heading" ADD COLUMN "icon_inverted" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_heading" ADD COLUMN "heading_level" "enum__pages_v_blocks_heading_heading_level" DEFAULT 'h2';
  ALTER TABLE "_pages_v_blocks_heading" ADD COLUMN "icon_inverted" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_heading" ADD COLUMN "heading_level" "enum_posts_blocks_heading_heading_level" DEFAULT 'h2';
  ALTER TABLE "posts_blocks_heading" ADD COLUMN "icon_inverted" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_heading" ADD COLUMN "heading_level" "enum__posts_v_blocks_heading_heading_level" DEFAULT 'h2';
  ALTER TABLE "_posts_v_blocks_heading" ADD COLUMN "icon_inverted" boolean DEFAULT false;
  ALTER TABLE "events_blocks_heading" ADD COLUMN "heading_level" "enum_events_blocks_heading_heading_level" DEFAULT 'h2';
  ALTER TABLE "events_blocks_heading" ADD COLUMN "icon_inverted" boolean DEFAULT false;
  ALTER TABLE "_events_v_blocks_heading" ADD COLUMN "heading_level" "enum__events_v_blocks_heading_heading_level" DEFAULT 'h2';
  ALTER TABLE "_events_v_blocks_heading" ADD COLUMN "icon_inverted" boolean DEFAULT false;
  ALTER TABLE "event_cycles_blocks_heading" ADD COLUMN "heading_level" "enum_event_cycles_blocks_heading_heading_level" DEFAULT 'h2';
  ALTER TABLE "event_cycles_blocks_heading" ADD COLUMN "icon_inverted" boolean DEFAULT false;
  ALTER TABLE "_event_cycles_v_blocks_heading" ADD COLUMN "heading_level" "enum__event_cycles_v_blocks_heading_heading_level" DEFAULT 'h2';
  ALTER TABLE "_event_cycles_v_blocks_heading" ADD COLUMN "icon_inverted" boolean DEFAULT false;
  ALTER TABLE "partners_blocks_heading" ADD COLUMN "heading_level" "enum_partners_blocks_heading_heading_level" DEFAULT 'h2';
  ALTER TABLE "partners_blocks_heading" ADD COLUMN "icon_inverted" boolean DEFAULT false;
  ALTER TABLE "_partners_v_blocks_heading" ADD COLUMN "heading_level" "enum__partners_v_blocks_heading_heading_level" DEFAULT 'h2';
  ALTER TABLE "_partners_v_blocks_heading" ADD COLUMN "icon_inverted" boolean DEFAULT false;
  ALTER TABLE "footer_columns" ADD COLUMN "alignment" "enum_footer_columns_alignment" DEFAULT 'left' NOT NULL;
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "heading_icon_name";
  ALTER TABLE "pages_blocks_listing" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_listing" DROP COLUMN "heading_icon_name";
  ALTER TABLE "pages_blocks_media_gallery" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_media_gallery" DROP COLUMN "heading_icon_name";
  ALTER TABLE "pages_blocks_documents" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_documents" DROP COLUMN "heading_icon_name";
  ALTER TABLE "pages_blocks_attachments" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_attachments" DROP COLUMN "heading_icon_name";
  ALTER TABLE "pages_blocks_member_profiles" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_member_profiles" DROP COLUMN "heading_icon_name";
  ALTER TABLE "pages_blocks_column_layout_columns" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_column_layout_columns" DROP COLUMN "heading_icon_name";
  ALTER TABLE "pages_blocks_column_layout" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_column_layout" DROP COLUMN "heading_icon_name";
  ALTER TABLE "pages_blocks_section_group_sections" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_section_group_sections" DROP COLUMN "heading_icon_name";
  ALTER TABLE "pages_blocks_section_group" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_section_group" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_pages_v_blocks_listing" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_listing" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_pages_v_blocks_media_gallery" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_media_gallery" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_pages_v_blocks_documents" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_documents" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_pages_v_blocks_attachments" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_attachments" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_pages_v_blocks_member_profiles" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_member_profiles" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_pages_v_blocks_column_layout_columns" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_column_layout_columns" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_pages_v_blocks_column_layout" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_column_layout" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_pages_v_blocks_section_group_sections" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_section_group_sections" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_pages_v_blocks_section_group" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_section_group" DROP COLUMN "heading_icon_name";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "heading";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "heading_icon_name";
  ALTER TABLE "posts_blocks_listing" DROP COLUMN "heading";
  ALTER TABLE "posts_blocks_listing" DROP COLUMN "heading_icon_name";
  ALTER TABLE "posts_blocks_media_gallery" DROP COLUMN "heading";
  ALTER TABLE "posts_blocks_media_gallery" DROP COLUMN "heading_icon_name";
  ALTER TABLE "posts_blocks_documents" DROP COLUMN "heading";
  ALTER TABLE "posts_blocks_documents" DROP COLUMN "heading_icon_name";
  ALTER TABLE "posts_blocks_attachments" DROP COLUMN "heading";
  ALTER TABLE "posts_blocks_attachments" DROP COLUMN "heading_icon_name";
  ALTER TABLE "posts_blocks_member_profiles" DROP COLUMN "heading";
  ALTER TABLE "posts_blocks_member_profiles" DROP COLUMN "heading_icon_name";
  ALTER TABLE "posts_blocks_column_layout_columns" DROP COLUMN "heading";
  ALTER TABLE "posts_blocks_column_layout_columns" DROP COLUMN "heading_icon_name";
  ALTER TABLE "posts_blocks_column_layout" DROP COLUMN "heading";
  ALTER TABLE "posts_blocks_column_layout" DROP COLUMN "heading_icon_name";
  ALTER TABLE "posts_blocks_section_group_sections" DROP COLUMN "heading";
  ALTER TABLE "posts_blocks_section_group_sections" DROP COLUMN "heading_icon_name";
  ALTER TABLE "posts_blocks_section_group" DROP COLUMN "heading";
  ALTER TABLE "posts_blocks_section_group" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "heading";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_posts_v_blocks_listing" DROP COLUMN "heading";
  ALTER TABLE "_posts_v_blocks_listing" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_posts_v_blocks_media_gallery" DROP COLUMN "heading";
  ALTER TABLE "_posts_v_blocks_media_gallery" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_posts_v_blocks_documents" DROP COLUMN "heading";
  ALTER TABLE "_posts_v_blocks_documents" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_posts_v_blocks_attachments" DROP COLUMN "heading";
  ALTER TABLE "_posts_v_blocks_attachments" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_posts_v_blocks_member_profiles" DROP COLUMN "heading";
  ALTER TABLE "_posts_v_blocks_member_profiles" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_posts_v_blocks_column_layout_columns" DROP COLUMN "heading";
  ALTER TABLE "_posts_v_blocks_column_layout_columns" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_posts_v_blocks_column_layout" DROP COLUMN "heading";
  ALTER TABLE "_posts_v_blocks_column_layout" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_posts_v_blocks_section_group_sections" DROP COLUMN "heading";
  ALTER TABLE "_posts_v_blocks_section_group_sections" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_posts_v_blocks_section_group" DROP COLUMN "heading";
  ALTER TABLE "_posts_v_blocks_section_group" DROP COLUMN "heading_icon_name";
  ALTER TABLE "events_blocks_rich_text" DROP COLUMN "heading";
  ALTER TABLE "events_blocks_rich_text" DROP COLUMN "heading_icon_name";
  ALTER TABLE "events_blocks_listing" DROP COLUMN "heading";
  ALTER TABLE "events_blocks_listing" DROP COLUMN "heading_icon_name";
  ALTER TABLE "events_blocks_media_gallery" DROP COLUMN "heading";
  ALTER TABLE "events_blocks_media_gallery" DROP COLUMN "heading_icon_name";
  ALTER TABLE "events_blocks_documents" DROP COLUMN "heading";
  ALTER TABLE "events_blocks_documents" DROP COLUMN "heading_icon_name";
  ALTER TABLE "events_blocks_attachments" DROP COLUMN "heading";
  ALTER TABLE "events_blocks_attachments" DROP COLUMN "heading_icon_name";
  ALTER TABLE "events_blocks_member_profiles" DROP COLUMN "heading";
  ALTER TABLE "events_blocks_member_profiles" DROP COLUMN "heading_icon_name";
  ALTER TABLE "events_blocks_column_layout_columns" DROP COLUMN "heading";
  ALTER TABLE "events_blocks_column_layout_columns" DROP COLUMN "heading_icon_name";
  ALTER TABLE "events_blocks_column_layout" DROP COLUMN "heading";
  ALTER TABLE "events_blocks_column_layout" DROP COLUMN "heading_icon_name";
  ALTER TABLE "events_blocks_section_group_sections" DROP COLUMN "heading";
  ALTER TABLE "events_blocks_section_group_sections" DROP COLUMN "heading_icon_name";
  ALTER TABLE "events_blocks_section_group" DROP COLUMN "heading";
  ALTER TABLE "events_blocks_section_group" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_events_v_blocks_rich_text" DROP COLUMN "heading";
  ALTER TABLE "_events_v_blocks_rich_text" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_events_v_blocks_listing" DROP COLUMN "heading";
  ALTER TABLE "_events_v_blocks_listing" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_events_v_blocks_media_gallery" DROP COLUMN "heading";
  ALTER TABLE "_events_v_blocks_media_gallery" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_events_v_blocks_documents" DROP COLUMN "heading";
  ALTER TABLE "_events_v_blocks_documents" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_events_v_blocks_attachments" DROP COLUMN "heading";
  ALTER TABLE "_events_v_blocks_attachments" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_events_v_blocks_member_profiles" DROP COLUMN "heading";
  ALTER TABLE "_events_v_blocks_member_profiles" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_events_v_blocks_column_layout_columns" DROP COLUMN "heading";
  ALTER TABLE "_events_v_blocks_column_layout_columns" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_events_v_blocks_column_layout" DROP COLUMN "heading";
  ALTER TABLE "_events_v_blocks_column_layout" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_events_v_blocks_section_group_sections" DROP COLUMN "heading";
  ALTER TABLE "_events_v_blocks_section_group_sections" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_events_v_blocks_section_group" DROP COLUMN "heading";
  ALTER TABLE "_events_v_blocks_section_group" DROP COLUMN "heading_icon_name";
  ALTER TABLE "event_cycles_blocks_rich_text" DROP COLUMN "heading";
  ALTER TABLE "event_cycles_blocks_rich_text" DROP COLUMN "heading_icon_name";
  ALTER TABLE "event_cycles_blocks_listing" DROP COLUMN "heading";
  ALTER TABLE "event_cycles_blocks_listing" DROP COLUMN "heading_icon_name";
  ALTER TABLE "event_cycles_blocks_media_gallery" DROP COLUMN "heading";
  ALTER TABLE "event_cycles_blocks_media_gallery" DROP COLUMN "heading_icon_name";
  ALTER TABLE "event_cycles_blocks_documents" DROP COLUMN "heading";
  ALTER TABLE "event_cycles_blocks_documents" DROP COLUMN "heading_icon_name";
  ALTER TABLE "event_cycles_blocks_attachments" DROP COLUMN "heading";
  ALTER TABLE "event_cycles_blocks_attachments" DROP COLUMN "heading_icon_name";
  ALTER TABLE "event_cycles_blocks_member_profiles" DROP COLUMN "heading";
  ALTER TABLE "event_cycles_blocks_member_profiles" DROP COLUMN "heading_icon_name";
  ALTER TABLE "event_cycles_blocks_column_layout_columns" DROP COLUMN "heading";
  ALTER TABLE "event_cycles_blocks_column_layout_columns" DROP COLUMN "heading_icon_name";
  ALTER TABLE "event_cycles_blocks_column_layout" DROP COLUMN "heading";
  ALTER TABLE "event_cycles_blocks_column_layout" DROP COLUMN "heading_icon_name";
  ALTER TABLE "event_cycles_blocks_section_group_sections" DROP COLUMN "heading";
  ALTER TABLE "event_cycles_blocks_section_group_sections" DROP COLUMN "heading_icon_name";
  ALTER TABLE "event_cycles_blocks_section_group" DROP COLUMN "heading";
  ALTER TABLE "event_cycles_blocks_section_group" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_event_cycles_v_blocks_rich_text" DROP COLUMN "heading";
  ALTER TABLE "_event_cycles_v_blocks_rich_text" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_event_cycles_v_blocks_listing" DROP COLUMN "heading";
  ALTER TABLE "_event_cycles_v_blocks_listing" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_event_cycles_v_blocks_media_gallery" DROP COLUMN "heading";
  ALTER TABLE "_event_cycles_v_blocks_media_gallery" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_event_cycles_v_blocks_documents" DROP COLUMN "heading";
  ALTER TABLE "_event_cycles_v_blocks_documents" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_event_cycles_v_blocks_attachments" DROP COLUMN "heading";
  ALTER TABLE "_event_cycles_v_blocks_attachments" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_event_cycles_v_blocks_member_profiles" DROP COLUMN "heading";
  ALTER TABLE "_event_cycles_v_blocks_member_profiles" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_event_cycles_v_blocks_column_layout_columns" DROP COLUMN "heading";
  ALTER TABLE "_event_cycles_v_blocks_column_layout_columns" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_event_cycles_v_blocks_column_layout" DROP COLUMN "heading";
  ALTER TABLE "_event_cycles_v_blocks_column_layout" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_event_cycles_v_blocks_section_group_sections" DROP COLUMN "heading";
  ALTER TABLE "_event_cycles_v_blocks_section_group_sections" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_event_cycles_v_blocks_section_group" DROP COLUMN "heading";
  ALTER TABLE "_event_cycles_v_blocks_section_group" DROP COLUMN "heading_icon_name";
  ALTER TABLE "partners_blocks_rich_text" DROP COLUMN "heading";
  ALTER TABLE "partners_blocks_rich_text" DROP COLUMN "heading_icon_name";
  ALTER TABLE "partners_blocks_listing" DROP COLUMN "heading";
  ALTER TABLE "partners_blocks_listing" DROP COLUMN "heading_icon_name";
  ALTER TABLE "partners_blocks_media_gallery" DROP COLUMN "heading";
  ALTER TABLE "partners_blocks_media_gallery" DROP COLUMN "heading_icon_name";
  ALTER TABLE "partners_blocks_documents" DROP COLUMN "heading";
  ALTER TABLE "partners_blocks_documents" DROP COLUMN "heading_icon_name";
  ALTER TABLE "partners_blocks_attachments" DROP COLUMN "heading";
  ALTER TABLE "partners_blocks_attachments" DROP COLUMN "heading_icon_name";
  ALTER TABLE "partners_blocks_member_profiles" DROP COLUMN "heading";
  ALTER TABLE "partners_blocks_member_profiles" DROP COLUMN "heading_icon_name";
  ALTER TABLE "partners_blocks_column_layout_columns" DROP COLUMN "heading";
  ALTER TABLE "partners_blocks_column_layout_columns" DROP COLUMN "heading_icon_name";
  ALTER TABLE "partners_blocks_column_layout" DROP COLUMN "heading";
  ALTER TABLE "partners_blocks_column_layout" DROP COLUMN "heading_icon_name";
  ALTER TABLE "partners_blocks_section_group_sections" DROP COLUMN "heading";
  ALTER TABLE "partners_blocks_section_group_sections" DROP COLUMN "heading_icon_name";
  ALTER TABLE "partners_blocks_section_group" DROP COLUMN "heading";
  ALTER TABLE "partners_blocks_section_group" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_partners_v_blocks_rich_text" DROP COLUMN "heading";
  ALTER TABLE "_partners_v_blocks_rich_text" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_partners_v_blocks_listing" DROP COLUMN "heading";
  ALTER TABLE "_partners_v_blocks_listing" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_partners_v_blocks_media_gallery" DROP COLUMN "heading";
  ALTER TABLE "_partners_v_blocks_media_gallery" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_partners_v_blocks_documents" DROP COLUMN "heading";
  ALTER TABLE "_partners_v_blocks_documents" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_partners_v_blocks_attachments" DROP COLUMN "heading";
  ALTER TABLE "_partners_v_blocks_attachments" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_partners_v_blocks_member_profiles" DROP COLUMN "heading";
  ALTER TABLE "_partners_v_blocks_member_profiles" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_partners_v_blocks_column_layout_columns" DROP COLUMN "heading";
  ALTER TABLE "_partners_v_blocks_column_layout_columns" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_partners_v_blocks_column_layout" DROP COLUMN "heading";
  ALTER TABLE "_partners_v_blocks_column_layout" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_partners_v_blocks_section_group_sections" DROP COLUMN "heading";
  ALTER TABLE "_partners_v_blocks_section_group_sections" DROP COLUMN "heading_icon_name";
  ALTER TABLE "_partners_v_blocks_section_group" DROP COLUMN "heading";
  ALTER TABLE "_partners_v_blocks_section_group" DROP COLUMN "heading_icon_name";
  DROP TYPE "public"."hd_icon";`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."hd_icon" AS ENUM('astronaut', 'bluesky', 'mace', 'time', 'dnd5', 'discord', 'document', 'mail', 'facebook', 'globe', 'star', 'instagram', 'calendar', 'gun', 'cards', 'collection', 'compass', 'confetti', 'dice', 'd10', 'd12', 'd20', 'd4', 'd6', 'd8', 'book', 'fireball', 'larp', 'external-link', 'linkedin', 'location', 'bow', 'mage', 'messenger', 'sword', 'image', 'announcement', 'partner', 'pdf', 'pawn', 'download', 'review', 'wand', 'sf', 'arrows', 'slack', 'users', 'star-trek', 'star-wars-empire', 'star-wars-rebel-alliance', 'steampunk', 'home', 'arrow', 'arrow-left', 'arrow-right', 'stormtrooper', 'tag', 'shield', 'axe', 'twitch', 'fighter', 'event', 'youtube');
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "heading" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "pages_blocks_listing" ADD COLUMN "heading" varchar;
  ALTER TABLE "pages_blocks_listing" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "pages_blocks_media_gallery" ADD COLUMN "heading" varchar;
  ALTER TABLE "pages_blocks_media_gallery" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "pages_blocks_documents" ADD COLUMN "heading" varchar;
  ALTER TABLE "pages_blocks_documents" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "pages_blocks_attachments" ADD COLUMN "heading" varchar;
  ALTER TABLE "pages_blocks_attachments" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "pages_blocks_member_profiles" ADD COLUMN "heading" varchar;
  ALTER TABLE "pages_blocks_member_profiles" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "pages_blocks_column_layout_columns" ADD COLUMN "heading" varchar;
  ALTER TABLE "pages_blocks_column_layout_columns" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "pages_blocks_column_layout" ADD COLUMN "heading" varchar;
  ALTER TABLE "pages_blocks_column_layout" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "pages_blocks_section_group_sections" ADD COLUMN "heading" varchar;
  ALTER TABLE "pages_blocks_section_group_sections" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "pages_blocks_section_group" ADD COLUMN "heading" varchar;
  ALTER TABLE "pages_blocks_section_group" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "heading" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_pages_v_blocks_listing" ADD COLUMN "heading" varchar;
  ALTER TABLE "_pages_v_blocks_listing" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_pages_v_blocks_media_gallery" ADD COLUMN "heading" varchar;
  ALTER TABLE "_pages_v_blocks_media_gallery" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_pages_v_blocks_documents" ADD COLUMN "heading" varchar;
  ALTER TABLE "_pages_v_blocks_documents" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_pages_v_blocks_attachments" ADD COLUMN "heading" varchar;
  ALTER TABLE "_pages_v_blocks_attachments" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_pages_v_blocks_member_profiles" ADD COLUMN "heading" varchar;
  ALTER TABLE "_pages_v_blocks_member_profiles" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_pages_v_blocks_column_layout_columns" ADD COLUMN "heading" varchar;
  ALTER TABLE "_pages_v_blocks_column_layout_columns" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_pages_v_blocks_column_layout" ADD COLUMN "heading" varchar;
  ALTER TABLE "_pages_v_blocks_column_layout" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_pages_v_blocks_section_group_sections" ADD COLUMN "heading" varchar;
  ALTER TABLE "_pages_v_blocks_section_group_sections" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_pages_v_blocks_section_group" ADD COLUMN "heading" varchar;
  ALTER TABLE "_pages_v_blocks_section_group" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "heading" varchar;
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "posts_blocks_listing" ADD COLUMN "heading" varchar;
  ALTER TABLE "posts_blocks_listing" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "posts_blocks_media_gallery" ADD COLUMN "heading" varchar;
  ALTER TABLE "posts_blocks_media_gallery" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "posts_blocks_documents" ADD COLUMN "heading" varchar;
  ALTER TABLE "posts_blocks_documents" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "posts_blocks_attachments" ADD COLUMN "heading" varchar;
  ALTER TABLE "posts_blocks_attachments" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "posts_blocks_member_profiles" ADD COLUMN "heading" varchar;
  ALTER TABLE "posts_blocks_member_profiles" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "posts_blocks_column_layout_columns" ADD COLUMN "heading" varchar;
  ALTER TABLE "posts_blocks_column_layout_columns" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "posts_blocks_column_layout" ADD COLUMN "heading" varchar;
  ALTER TABLE "posts_blocks_column_layout" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "posts_blocks_section_group_sections" ADD COLUMN "heading" varchar;
  ALTER TABLE "posts_blocks_section_group_sections" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "posts_blocks_section_group" ADD COLUMN "heading" varchar;
  ALTER TABLE "posts_blocks_section_group" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "heading" varchar;
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_posts_v_blocks_listing" ADD COLUMN "heading" varchar;
  ALTER TABLE "_posts_v_blocks_listing" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_posts_v_blocks_media_gallery" ADD COLUMN "heading" varchar;
  ALTER TABLE "_posts_v_blocks_media_gallery" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_posts_v_blocks_documents" ADD COLUMN "heading" varchar;
  ALTER TABLE "_posts_v_blocks_documents" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_posts_v_blocks_attachments" ADD COLUMN "heading" varchar;
  ALTER TABLE "_posts_v_blocks_attachments" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_posts_v_blocks_member_profiles" ADD COLUMN "heading" varchar;
  ALTER TABLE "_posts_v_blocks_member_profiles" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_posts_v_blocks_column_layout_columns" ADD COLUMN "heading" varchar;
  ALTER TABLE "_posts_v_blocks_column_layout_columns" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_posts_v_blocks_column_layout" ADD COLUMN "heading" varchar;
  ALTER TABLE "_posts_v_blocks_column_layout" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_posts_v_blocks_section_group_sections" ADD COLUMN "heading" varchar;
  ALTER TABLE "_posts_v_blocks_section_group_sections" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_posts_v_blocks_section_group" ADD COLUMN "heading" varchar;
  ALTER TABLE "_posts_v_blocks_section_group" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "events_blocks_rich_text" ADD COLUMN "heading" varchar;
  ALTER TABLE "events_blocks_rich_text" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "events_blocks_listing" ADD COLUMN "heading" varchar;
  ALTER TABLE "events_blocks_listing" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "events_blocks_media_gallery" ADD COLUMN "heading" varchar;
  ALTER TABLE "events_blocks_media_gallery" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "events_blocks_documents" ADD COLUMN "heading" varchar;
  ALTER TABLE "events_blocks_documents" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "events_blocks_attachments" ADD COLUMN "heading" varchar;
  ALTER TABLE "events_blocks_attachments" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "events_blocks_member_profiles" ADD COLUMN "heading" varchar;
  ALTER TABLE "events_blocks_member_profiles" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "events_blocks_column_layout_columns" ADD COLUMN "heading" varchar;
  ALTER TABLE "events_blocks_column_layout_columns" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "events_blocks_column_layout" ADD COLUMN "heading" varchar;
  ALTER TABLE "events_blocks_column_layout" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "events_blocks_section_group_sections" ADD COLUMN "heading" varchar;
  ALTER TABLE "events_blocks_section_group_sections" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "events_blocks_section_group" ADD COLUMN "heading" varchar;
  ALTER TABLE "events_blocks_section_group" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_events_v_blocks_rich_text" ADD COLUMN "heading" varchar;
  ALTER TABLE "_events_v_blocks_rich_text" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_events_v_blocks_listing" ADD COLUMN "heading" varchar;
  ALTER TABLE "_events_v_blocks_listing" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_events_v_blocks_media_gallery" ADD COLUMN "heading" varchar;
  ALTER TABLE "_events_v_blocks_media_gallery" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_events_v_blocks_documents" ADD COLUMN "heading" varchar;
  ALTER TABLE "_events_v_blocks_documents" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_events_v_blocks_attachments" ADD COLUMN "heading" varchar;
  ALTER TABLE "_events_v_blocks_attachments" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_events_v_blocks_member_profiles" ADD COLUMN "heading" varchar;
  ALTER TABLE "_events_v_blocks_member_profiles" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_events_v_blocks_column_layout_columns" ADD COLUMN "heading" varchar;
  ALTER TABLE "_events_v_blocks_column_layout_columns" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_events_v_blocks_column_layout" ADD COLUMN "heading" varchar;
  ALTER TABLE "_events_v_blocks_column_layout" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_events_v_blocks_section_group_sections" ADD COLUMN "heading" varchar;
  ALTER TABLE "_events_v_blocks_section_group_sections" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_events_v_blocks_section_group" ADD COLUMN "heading" varchar;
  ALTER TABLE "_events_v_blocks_section_group" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "event_cycles_blocks_rich_text" ADD COLUMN "heading" varchar;
  ALTER TABLE "event_cycles_blocks_rich_text" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "event_cycles_blocks_listing" ADD COLUMN "heading" varchar;
  ALTER TABLE "event_cycles_blocks_listing" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "event_cycles_blocks_media_gallery" ADD COLUMN "heading" varchar;
  ALTER TABLE "event_cycles_blocks_media_gallery" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "event_cycles_blocks_documents" ADD COLUMN "heading" varchar;
  ALTER TABLE "event_cycles_blocks_documents" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "event_cycles_blocks_attachments" ADD COLUMN "heading" varchar;
  ALTER TABLE "event_cycles_blocks_attachments" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "event_cycles_blocks_member_profiles" ADD COLUMN "heading" varchar;
  ALTER TABLE "event_cycles_blocks_member_profiles" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "event_cycles_blocks_column_layout_columns" ADD COLUMN "heading" varchar;
  ALTER TABLE "event_cycles_blocks_column_layout_columns" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "event_cycles_blocks_column_layout" ADD COLUMN "heading" varchar;
  ALTER TABLE "event_cycles_blocks_column_layout" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "event_cycles_blocks_section_group_sections" ADD COLUMN "heading" varchar;
  ALTER TABLE "event_cycles_blocks_section_group_sections" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "event_cycles_blocks_section_group" ADD COLUMN "heading" varchar;
  ALTER TABLE "event_cycles_blocks_section_group" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_event_cycles_v_blocks_rich_text" ADD COLUMN "heading" varchar;
  ALTER TABLE "_event_cycles_v_blocks_rich_text" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_event_cycles_v_blocks_listing" ADD COLUMN "heading" varchar;
  ALTER TABLE "_event_cycles_v_blocks_listing" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_event_cycles_v_blocks_media_gallery" ADD COLUMN "heading" varchar;
  ALTER TABLE "_event_cycles_v_blocks_media_gallery" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_event_cycles_v_blocks_documents" ADD COLUMN "heading" varchar;
  ALTER TABLE "_event_cycles_v_blocks_documents" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_event_cycles_v_blocks_attachments" ADD COLUMN "heading" varchar;
  ALTER TABLE "_event_cycles_v_blocks_attachments" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_event_cycles_v_blocks_member_profiles" ADD COLUMN "heading" varchar;
  ALTER TABLE "_event_cycles_v_blocks_member_profiles" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_event_cycles_v_blocks_column_layout_columns" ADD COLUMN "heading" varchar;
  ALTER TABLE "_event_cycles_v_blocks_column_layout_columns" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_event_cycles_v_blocks_column_layout" ADD COLUMN "heading" varchar;
  ALTER TABLE "_event_cycles_v_blocks_column_layout" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_event_cycles_v_blocks_section_group_sections" ADD COLUMN "heading" varchar;
  ALTER TABLE "_event_cycles_v_blocks_section_group_sections" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_event_cycles_v_blocks_section_group" ADD COLUMN "heading" varchar;
  ALTER TABLE "_event_cycles_v_blocks_section_group" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "partners_blocks_rich_text" ADD COLUMN "heading" varchar;
  ALTER TABLE "partners_blocks_rich_text" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "partners_blocks_listing" ADD COLUMN "heading" varchar;
  ALTER TABLE "partners_blocks_listing" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "partners_blocks_media_gallery" ADD COLUMN "heading" varchar;
  ALTER TABLE "partners_blocks_media_gallery" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "partners_blocks_documents" ADD COLUMN "heading" varchar;
  ALTER TABLE "partners_blocks_documents" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "partners_blocks_attachments" ADD COLUMN "heading" varchar;
  ALTER TABLE "partners_blocks_attachments" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "partners_blocks_member_profiles" ADD COLUMN "heading" varchar;
  ALTER TABLE "partners_blocks_member_profiles" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "partners_blocks_column_layout_columns" ADD COLUMN "heading" varchar;
  ALTER TABLE "partners_blocks_column_layout_columns" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "partners_blocks_column_layout" ADD COLUMN "heading" varchar;
  ALTER TABLE "partners_blocks_column_layout" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "partners_blocks_section_group_sections" ADD COLUMN "heading" varchar;
  ALTER TABLE "partners_blocks_section_group_sections" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "partners_blocks_section_group" ADD COLUMN "heading" varchar;
  ALTER TABLE "partners_blocks_section_group" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_partners_v_blocks_rich_text" ADD COLUMN "heading" varchar;
  ALTER TABLE "_partners_v_blocks_rich_text" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_partners_v_blocks_listing" ADD COLUMN "heading" varchar;
  ALTER TABLE "_partners_v_blocks_listing" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_partners_v_blocks_media_gallery" ADD COLUMN "heading" varchar;
  ALTER TABLE "_partners_v_blocks_media_gallery" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_partners_v_blocks_documents" ADD COLUMN "heading" varchar;
  ALTER TABLE "_partners_v_blocks_documents" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_partners_v_blocks_attachments" ADD COLUMN "heading" varchar;
  ALTER TABLE "_partners_v_blocks_attachments" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_partners_v_blocks_member_profiles" ADD COLUMN "heading" varchar;
  ALTER TABLE "_partners_v_blocks_member_profiles" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_partners_v_blocks_column_layout_columns" ADD COLUMN "heading" varchar;
  ALTER TABLE "_partners_v_blocks_column_layout_columns" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_partners_v_blocks_column_layout" ADD COLUMN "heading" varchar;
  ALTER TABLE "_partners_v_blocks_column_layout" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_partners_v_blocks_section_group_sections" ADD COLUMN "heading" varchar;
  ALTER TABLE "_partners_v_blocks_section_group_sections" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "_partners_v_blocks_section_group" ADD COLUMN "heading" varchar;
  ALTER TABLE "_partners_v_blocks_section_group" ADD COLUMN "heading_icon_name" "hd_icon";
  ALTER TABLE "pages_blocks_heading" DROP COLUMN "heading_level";
  ALTER TABLE "pages_blocks_heading" DROP COLUMN "icon_inverted";
  ALTER TABLE "_pages_v_blocks_heading" DROP COLUMN "heading_level";
  ALTER TABLE "_pages_v_blocks_heading" DROP COLUMN "icon_inverted";
  ALTER TABLE "posts_blocks_heading" DROP COLUMN "heading_level";
  ALTER TABLE "posts_blocks_heading" DROP COLUMN "icon_inverted";
  ALTER TABLE "_posts_v_blocks_heading" DROP COLUMN "heading_level";
  ALTER TABLE "_posts_v_blocks_heading" DROP COLUMN "icon_inverted";
  ALTER TABLE "events_blocks_heading" DROP COLUMN "heading_level";
  ALTER TABLE "events_blocks_heading" DROP COLUMN "icon_inverted";
  ALTER TABLE "_events_v_blocks_heading" DROP COLUMN "heading_level";
  ALTER TABLE "_events_v_blocks_heading" DROP COLUMN "icon_inverted";
  ALTER TABLE "event_cycles_blocks_heading" DROP COLUMN "heading_level";
  ALTER TABLE "event_cycles_blocks_heading" DROP COLUMN "icon_inverted";
  ALTER TABLE "_event_cycles_v_blocks_heading" DROP COLUMN "heading_level";
  ALTER TABLE "_event_cycles_v_blocks_heading" DROP COLUMN "icon_inverted";
  ALTER TABLE "partners_blocks_heading" DROP COLUMN "heading_level";
  ALTER TABLE "partners_blocks_heading" DROP COLUMN "icon_inverted";
  ALTER TABLE "_partners_v_blocks_heading" DROP COLUMN "heading_level";
  ALTER TABLE "_partners_v_blocks_heading" DROP COLUMN "icon_inverted";
  ALTER TABLE "footer_columns" DROP COLUMN "alignment";
  DROP TYPE "public"."enum_pages_blocks_heading_heading_level";
  DROP TYPE "public"."enum__pages_v_blocks_heading_heading_level";
  DROP TYPE "public"."enum_posts_blocks_heading_heading_level";
  DROP TYPE "public"."enum__posts_v_blocks_heading_heading_level";
  DROP TYPE "public"."enum_events_blocks_heading_heading_level";
  DROP TYPE "public"."enum__events_v_blocks_heading_heading_level";
  DROP TYPE "public"."enum_event_cycles_blocks_heading_heading_level";
  DROP TYPE "public"."enum__event_cycles_v_blocks_heading_heading_level";
  DROP TYPE "public"."enum_partners_blocks_heading_heading_level";
  DROP TYPE "public"."enum__partners_v_blocks_heading_heading_level";
  DROP TYPE "public"."enum_footer_columns_alignment";`)
}
