import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_pages_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "posts_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_posts_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_posts_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "events_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "events_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "events_external_links" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "events_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_events_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_events_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_events_v_version_external_links" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_events_v_version_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "event_cycles_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "event_cycles_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "event_cycles_event_defaults_external_links" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "event_cycles_event_defaults_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_event_cycles_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_event_cycles_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_event_cycles_v_version_event_defaults_external_links" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_event_cycles_v_version_event_defaults_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "partners_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "partners_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_partners_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_partners_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."target";
  CREATE TYPE "public"."target" AS ENUM('eventCycle', 'document', 'siteContactEmail', 'category', 'partner', 'page', 'tag', 'custom', 'post', 'event');
  ALTER TABLE "pages_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "pages_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_pages_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_pages_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "posts_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "posts_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_posts_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_posts_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "events_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "events_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "events_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "events_external_links" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_events_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_events_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_events_v_version_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_events_v_version_external_links" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "event_cycles_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "event_cycles_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "event_cycles_event_defaults_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "event_cycles_event_defaults_external_links" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_event_cycles_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_event_cycles_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_event_cycles_v_version_event_defaults_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_event_cycles_v_version_event_defaults_external_links" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "partners_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "partners_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_partners_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_partners_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "club_sections_menu_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "club_sections_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_club_sections_menu_items_target_type";
  CREATE TYPE "public"."enum_club_sections_menu_items_target_type" AS ENUM('eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'custom', 'post', 'event');
  ALTER TABLE "club_sections_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_club_sections_menu_items_target_type";
  ALTER TABLE "club_sections_menu_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_club_sections_menu_items_target_type" USING "target_type"::"public"."enum_club_sections_menu_items_target_type";
  ALTER TABLE "_club_sections_v_version_menu_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_club_sections_v_version_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum__club_sections_v_version_menu_items_target_type";
  CREATE TYPE "public"."enum__club_sections_v_version_menu_items_target_type" AS ENUM('eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'custom', 'post', 'event');
  ALTER TABLE "_club_sections_v_version_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum__club_sections_v_version_menu_items_target_type";
  ALTER TABLE "_club_sections_v_version_menu_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum__club_sections_v_version_menu_items_target_type" USING "target_type"::"public"."enum__club_sections_v_version_menu_items_target_type";
  ALTER TABLE "navigation_header_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "navigation_header_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_navigation_header_items_target_type";
  CREATE TYPE "public"."enum_navigation_header_items_target_type" AS ENUM('eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'custom', 'post', 'event');
  ALTER TABLE "navigation_header_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_navigation_header_items_target_type";
  ALTER TABLE "navigation_header_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_navigation_header_items_target_type" USING "target_type"::"public"."enum_navigation_header_items_target_type";
  ALTER TABLE "homepage_hero_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "homepage_hero_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_homepage_hero_items_target_type";
  CREATE TYPE "public"."enum_homepage_hero_items_target_type" AS ENUM('eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'custom', 'post', 'event');
  ALTER TABLE "homepage_hero_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_homepage_hero_items_target_type";
  ALTER TABLE "homepage_hero_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_homepage_hero_items_target_type" USING "target_type"::"public"."enum_homepage_hero_items_target_type";
  ALTER TABLE "homepage_sections_groups_menu_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "homepage_sections_groups_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_homepage_sections_groups_menu_items_target_type";
  CREATE TYPE "public"."enum_homepage_sections_groups_menu_items_target_type" AS ENUM('eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'custom', 'post', 'event');
  ALTER TABLE "homepage_sections_groups_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_homepage_sections_groups_menu_items_target_type";
  ALTER TABLE "homepage_sections_groups_menu_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_homepage_sections_groups_menu_items_target_type" USING "target_type"::"public"."enum_homepage_sections_groups_menu_items_target_type";
  ALTER TABLE "footer_social_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "footer_social_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_footer_social_items_target_type";
  CREATE TYPE "public"."enum_footer_social_items_target_type" AS ENUM('eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'custom', 'post', 'event');
  ALTER TABLE "footer_social_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_footer_social_items_target_type";
  ALTER TABLE "footer_social_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_footer_social_items_target_type" USING "target_type"::"public"."enum_footer_social_items_target_type";
  ALTER TABLE "footer_columns_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "footer_columns_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_footer_columns_items_target_type";
  CREATE TYPE "public"."enum_footer_columns_items_target_type" AS ENUM('eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'custom', 'post', 'event');
  ALTER TABLE "footer_columns_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_footer_columns_items_target_type";
  ALTER TABLE "footer_columns_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_footer_columns_items_target_type" USING "target_type"::"public"."enum_footer_columns_items_target_type";
  ALTER TABLE "pages_blocks_action_links_items" DROP COLUMN "accessible_label";
  ALTER TABLE "_pages_v_blocks_action_links_items" DROP COLUMN "accessible_label";
  ALTER TABLE "posts_blocks_action_links_items" DROP COLUMN "accessible_label";
  ALTER TABLE "_posts_v_blocks_action_links_items" DROP COLUMN "accessible_label";
  ALTER TABLE "events_blocks_action_links_items" DROP COLUMN "accessible_label";
  ALTER TABLE "_events_v_blocks_action_links_items" DROP COLUMN "accessible_label";
  ALTER TABLE "event_cycles_blocks_action_links_items" DROP COLUMN "accessible_label";
  ALTER TABLE "_event_cycles_v_blocks_action_links_items" DROP COLUMN "accessible_label";
  ALTER TABLE "partners_blocks_action_links_items" DROP COLUMN "accessible_label";
  ALTER TABLE "_partners_v_blocks_action_links_items" DROP COLUMN "accessible_label";
  ALTER TABLE "club_sections_menu_items" DROP COLUMN "accessible_label";
  ALTER TABLE "_club_sections_v_version_menu_items" DROP COLUMN "accessible_label";
  ALTER TABLE "navigation_header_items" DROP COLUMN "accessible_label";
  ALTER TABLE "homepage_hero_items" DROP COLUMN "accessible_label";
  ALTER TABLE "homepage_sections_groups_menu_items" DROP COLUMN "accessible_label";
  ALTER TABLE "footer_social_items" DROP COLUMN "accessible_label";
  ALTER TABLE "footer_columns_items" DROP COLUMN "accessible_label";`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_pages_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "posts_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_posts_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_posts_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "events_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "events_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "events_external_links" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "events_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_events_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_events_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_events_v_version_external_links" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_events_v_version_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "event_cycles_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "event_cycles_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "event_cycles_event_defaults_external_links" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "event_cycles_event_defaults_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_event_cycles_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_event_cycles_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_event_cycles_v_version_event_defaults_external_links" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_event_cycles_v_version_event_defaults_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "partners_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "partners_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  ALTER TABLE "_partners_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_partners_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."target";
  CREATE TYPE "public"."target" AS ENUM('custom', 'eventCycle', 'document', 'category', 'partner', 'siteContactEmail', 'page', 'tag', 'post', 'event');
  ALTER TABLE "pages_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "pages_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_pages_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_pages_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "posts_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "posts_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_posts_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_posts_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "events_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "events_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "events_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "events_external_links" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_events_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_events_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_events_v_version_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_events_v_version_external_links" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "event_cycles_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "event_cycles_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "event_cycles_event_defaults_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "event_cycles_event_defaults_external_links" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_event_cycles_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_event_cycles_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_event_cycles_v_version_event_defaults_external_links" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_event_cycles_v_version_event_defaults_external_links" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "partners_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "partners_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "_partners_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."target";
  ALTER TABLE "_partners_v_blocks_action_links_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."target" USING "target_type"::"public"."target";
  ALTER TABLE "club_sections_menu_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "club_sections_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_club_sections_menu_items_target_type";
  CREATE TYPE "public"."enum_club_sections_menu_items_target_type" AS ENUM('custom', 'eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'post', 'event');
  ALTER TABLE "club_sections_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_club_sections_menu_items_target_type";
  ALTER TABLE "club_sections_menu_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_club_sections_menu_items_target_type" USING "target_type"::"public"."enum_club_sections_menu_items_target_type";
  ALTER TABLE "_club_sections_v_version_menu_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "_club_sections_v_version_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum__club_sections_v_version_menu_items_target_type";
  CREATE TYPE "public"."enum__club_sections_v_version_menu_items_target_type" AS ENUM('custom', 'eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'post', 'event');
  ALTER TABLE "_club_sections_v_version_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum__club_sections_v_version_menu_items_target_type";
  ALTER TABLE "_club_sections_v_version_menu_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum__club_sections_v_version_menu_items_target_type" USING "target_type"::"public"."enum__club_sections_v_version_menu_items_target_type";
  ALTER TABLE "navigation_header_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "navigation_header_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_navigation_header_items_target_type";
  CREATE TYPE "public"."enum_navigation_header_items_target_type" AS ENUM('custom', 'eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'post', 'event');
  ALTER TABLE "navigation_header_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_navigation_header_items_target_type";
  ALTER TABLE "navigation_header_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_navigation_header_items_target_type" USING "target_type"::"public"."enum_navigation_header_items_target_type";
  ALTER TABLE "homepage_hero_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "homepage_hero_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_homepage_hero_items_target_type";
  CREATE TYPE "public"."enum_homepage_hero_items_target_type" AS ENUM('custom', 'eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'post', 'event');
  ALTER TABLE "homepage_hero_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_homepage_hero_items_target_type";
  ALTER TABLE "homepage_hero_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_homepage_hero_items_target_type" USING "target_type"::"public"."enum_homepage_hero_items_target_type";
  ALTER TABLE "homepage_sections_groups_menu_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "homepage_sections_groups_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_homepage_sections_groups_menu_items_target_type";
  CREATE TYPE "public"."enum_homepage_sections_groups_menu_items_target_type" AS ENUM('custom', 'eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'post', 'event');
  ALTER TABLE "homepage_sections_groups_menu_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_homepage_sections_groups_menu_items_target_type";
  ALTER TABLE "homepage_sections_groups_menu_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_homepage_sections_groups_menu_items_target_type" USING "target_type"::"public"."enum_homepage_sections_groups_menu_items_target_type";
  ALTER TABLE "footer_social_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "footer_social_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_footer_social_items_target_type";
  CREATE TYPE "public"."enum_footer_social_items_target_type" AS ENUM('custom', 'eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'post', 'event');
  ALTER TABLE "footer_social_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_footer_social_items_target_type";
  ALTER TABLE "footer_social_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_footer_social_items_target_type" USING "target_type"::"public"."enum_footer_social_items_target_type";
  ALTER TABLE "footer_columns_items" ALTER COLUMN "target_type" SET DATA TYPE text;
  ALTER TABLE "footer_columns_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::text;
  DROP TYPE "public"."enum_footer_columns_items_target_type";
  CREATE TYPE "public"."enum_footer_columns_items_target_type" AS ENUM('custom', 'eventCycle', 'document', 'category', 'partner', 'page', 'tag', 'post', 'event');
  ALTER TABLE "footer_columns_items" ALTER COLUMN "target_type" SET DEFAULT 'custom'::"public"."enum_footer_columns_items_target_type";
  ALTER TABLE "footer_columns_items" ALTER COLUMN "target_type" SET DATA TYPE "public"."enum_footer_columns_items_target_type" USING "target_type"::"public"."enum_footer_columns_items_target_type";
  ALTER TABLE "pages_blocks_action_links_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "_pages_v_blocks_action_links_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "posts_blocks_action_links_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "_posts_v_blocks_action_links_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "events_blocks_action_links_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "_events_v_blocks_action_links_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "event_cycles_blocks_action_links_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "_event_cycles_v_blocks_action_links_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "partners_blocks_action_links_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "_partners_v_blocks_action_links_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "club_sections_menu_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "_club_sections_v_version_menu_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "navigation_header_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "homepage_hero_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "homepage_sections_groups_menu_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "footer_social_items" ADD COLUMN "accessible_label" varchar;
  ALTER TABLE "footer_columns_items" ADD COLUMN "accessible_label" varchar;`)
}
