import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'astronaut' BEFORE 'bluesky';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'mace' BEFORE 'time';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'dnd5' BEFORE 'discord';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'gun' BEFORE 'cards';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'compass' BEFORE 'dice';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'confetti' BEFORE 'dice';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'd10' BEFORE 'book';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'd12' BEFORE 'book';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'd20' BEFORE 'book';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'd4' BEFORE 'book';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'd6' BEFORE 'book';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'd8' BEFORE 'book';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'fireball' BEFORE 'external-link';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'bow' BEFORE 'larp-mask';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'mage' BEFORE 'larp-mask';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'wand' BEFORE 'slack';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'sf' BEFORE 'slack';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'arrows' BEFORE 'slack';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'star-trek' BEFORE 'home';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'star-wars-empire' BEFORE 'home';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'star-wars-rebel-alliance' BEFORE 'home';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'steampunk' BEFORE 'home';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'arrow' BEFORE 'arrow-right';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'arrow-left' BEFORE 'arrow-right';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'stormtrooper' BEFORE 'tag';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'shield' BEFORE 'twitch';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'axe' BEFORE 'twitch';
  ALTER TYPE "public"."enum_club_sections_menu_items_icon_name" ADD VALUE 'fighter' BEFORE 'event';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'astronaut' BEFORE 'bluesky';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'mace' BEFORE 'time';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'dnd5' BEFORE 'discord';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'gun' BEFORE 'cards';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'compass' BEFORE 'dice';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'confetti' BEFORE 'dice';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'd10' BEFORE 'book';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'd12' BEFORE 'book';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'd20' BEFORE 'book';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'd4' BEFORE 'book';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'd6' BEFORE 'book';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'd8' BEFORE 'book';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'fireball' BEFORE 'external-link';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'bow' BEFORE 'larp-mask';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'mage' BEFORE 'larp-mask';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'wand' BEFORE 'slack';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'sf' BEFORE 'slack';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'arrows' BEFORE 'slack';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'star-trek' BEFORE 'home';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'star-wars-empire' BEFORE 'home';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'star-wars-rebel-alliance' BEFORE 'home';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'steampunk' BEFORE 'home';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'arrow' BEFORE 'arrow-right';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'arrow-left' BEFORE 'arrow-right';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'stormtrooper' BEFORE 'tag';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'shield' BEFORE 'twitch';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'axe' BEFORE 'twitch';
  ALTER TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" ADD VALUE 'fighter' BEFORE 'event';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'astronaut' BEFORE 'bluesky';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'mace' BEFORE 'time';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'dnd5' BEFORE 'discord';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'gun' BEFORE 'cards';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'compass' BEFORE 'dice';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'confetti' BEFORE 'dice';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'd10' BEFORE 'book';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'd12' BEFORE 'book';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'd20' BEFORE 'book';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'd4' BEFORE 'book';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'd6' BEFORE 'book';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'd8' BEFORE 'book';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'fireball' BEFORE 'external-link';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'bow' BEFORE 'larp-mask';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'mage' BEFORE 'larp-mask';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'wand' BEFORE 'slack';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'sf' BEFORE 'slack';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'arrows' BEFORE 'slack';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'star-trek' BEFORE 'home';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'star-wars-empire' BEFORE 'home';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'star-wars-rebel-alliance' BEFORE 'home';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'steampunk' BEFORE 'home';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'arrow' BEFORE 'arrow-right';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'arrow-left' BEFORE 'arrow-right';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'stormtrooper' BEFORE 'tag';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'shield' BEFORE 'twitch';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'axe' BEFORE 'twitch';
  ALTER TYPE "public"."enum_navigation_header_items_icon_name" ADD VALUE 'fighter' BEFORE 'event';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'astronaut' BEFORE 'bluesky';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'mace' BEFORE 'time';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'dnd5' BEFORE 'discord';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'gun' BEFORE 'cards';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'compass' BEFORE 'dice';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'confetti' BEFORE 'dice';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'd10' BEFORE 'book';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'd12' BEFORE 'book';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'd20' BEFORE 'book';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'd4' BEFORE 'book';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'd6' BEFORE 'book';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'd8' BEFORE 'book';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'fireball' BEFORE 'external-link';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'bow' BEFORE 'larp-mask';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'mage' BEFORE 'larp-mask';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'wand' BEFORE 'slack';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'sf' BEFORE 'slack';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'arrows' BEFORE 'slack';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'star-trek' BEFORE 'home';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'star-wars-empire' BEFORE 'home';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'star-wars-rebel-alliance' BEFORE 'home';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'steampunk' BEFORE 'home';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'arrow' BEFORE 'arrow-right';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'arrow-left' BEFORE 'arrow-right';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'stormtrooper' BEFORE 'tag';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'shield' BEFORE 'twitch';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'axe' BEFORE 'twitch';
  ALTER TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" ADD VALUE 'fighter' BEFORE 'event';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'astronaut' BEFORE 'bluesky';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'mace' BEFORE 'time';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'dnd5' BEFORE 'discord';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'gun' BEFORE 'cards';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'compass' BEFORE 'dice';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'confetti' BEFORE 'dice';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'd10' BEFORE 'book';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'd12' BEFORE 'book';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'd20' BEFORE 'book';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'd4' BEFORE 'book';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'd6' BEFORE 'book';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'd8' BEFORE 'book';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'fireball' BEFORE 'external-link';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'bow' BEFORE 'larp-mask';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'mage' BEFORE 'larp-mask';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'wand' BEFORE 'slack';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'sf' BEFORE 'slack';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'arrows' BEFORE 'slack';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'star-trek' BEFORE 'home';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'star-wars-empire' BEFORE 'home';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'star-wars-rebel-alliance' BEFORE 'home';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'steampunk' BEFORE 'home';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'arrow' BEFORE 'arrow-right';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'arrow-left' BEFORE 'arrow-right';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'stormtrooper' BEFORE 'tag';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'shield' BEFORE 'twitch';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'axe' BEFORE 'twitch';
  ALTER TYPE "public"."enum_footer_social_items_icon_name" ADD VALUE 'fighter' BEFORE 'event';`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "club_sections_menu_items" ALTER COLUMN "icon_name" SET DATA TYPE text;
  DROP TYPE "public"."enum_club_sections_menu_items_icon_name";
  CREATE TYPE "public"."enum_club_sections_menu_items_icon_name" AS ENUM('bluesky', 'time', 'discord', 'document', 'mail', 'facebook', 'globe', 'star', 'instagram', 'calendar', 'cards', 'collection', 'dice', 'book', 'external-link', 'linkedin', 'location', 'larp-mask', 'messenger', 'sword', 'image', 'announcement', 'partner', 'pdf', 'pawn', 'download', 'review', 'slack', 'users', 'home', 'arrow-right', 'tag', 'twitch', 'event', 'youtube');
  ALTER TABLE "club_sections_menu_items" ALTER COLUMN "icon_name" SET DATA TYPE "public"."enum_club_sections_menu_items_icon_name" USING "icon_name"::"public"."enum_club_sections_menu_items_icon_name";
  ALTER TABLE "_club_sections_v_version_menu_items" ALTER COLUMN "icon_name" SET DATA TYPE text;
  DROP TYPE "public"."enum__club_sections_v_version_menu_items_icon_name";
  CREATE TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" AS ENUM('bluesky', 'time', 'discord', 'document', 'mail', 'facebook', 'globe', 'star', 'instagram', 'calendar', 'cards', 'collection', 'dice', 'book', 'external-link', 'linkedin', 'location', 'larp-mask', 'messenger', 'sword', 'image', 'announcement', 'partner', 'pdf', 'pawn', 'download', 'review', 'slack', 'users', 'home', 'arrow-right', 'tag', 'twitch', 'event', 'youtube');
  ALTER TABLE "_club_sections_v_version_menu_items" ALTER COLUMN "icon_name" SET DATA TYPE "public"."enum__club_sections_v_version_menu_items_icon_name" USING "icon_name"::"public"."enum__club_sections_v_version_menu_items_icon_name";
  ALTER TABLE "navigation_header_items" ALTER COLUMN "icon_name" SET DATA TYPE text;
  DROP TYPE "public"."enum_navigation_header_items_icon_name";
  CREATE TYPE "public"."enum_navigation_header_items_icon_name" AS ENUM('bluesky', 'time', 'discord', 'document', 'mail', 'facebook', 'globe', 'star', 'instagram', 'calendar', 'cards', 'collection', 'dice', 'book', 'external-link', 'linkedin', 'location', 'larp-mask', 'messenger', 'sword', 'image', 'announcement', 'partner', 'pdf', 'pawn', 'download', 'review', 'slack', 'users', 'home', 'arrow-right', 'tag', 'twitch', 'event', 'youtube');
  ALTER TABLE "navigation_header_items" ALTER COLUMN "icon_name" SET DATA TYPE "public"."enum_navigation_header_items_icon_name" USING "icon_name"::"public"."enum_navigation_header_items_icon_name";
  ALTER TABLE "homepage_sections_groups_menu_items" ALTER COLUMN "icon_name" SET DATA TYPE text;
  DROP TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name";
  CREATE TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" AS ENUM('bluesky', 'time', 'discord', 'document', 'mail', 'facebook', 'globe', 'star', 'instagram', 'calendar', 'cards', 'collection', 'dice', 'book', 'external-link', 'linkedin', 'location', 'larp-mask', 'messenger', 'sword', 'image', 'announcement', 'partner', 'pdf', 'pawn', 'download', 'review', 'slack', 'users', 'home', 'arrow-right', 'tag', 'twitch', 'event', 'youtube');
  ALTER TABLE "homepage_sections_groups_menu_items" ALTER COLUMN "icon_name" SET DATA TYPE "public"."enum_homepage_sections_groups_menu_items_icon_name" USING "icon_name"::"public"."enum_homepage_sections_groups_menu_items_icon_name";
  ALTER TABLE "footer_social_items" ALTER COLUMN "icon_name" SET DATA TYPE text;
  DROP TYPE "public"."enum_footer_social_items_icon_name";
  CREATE TYPE "public"."enum_footer_social_items_icon_name" AS ENUM('bluesky', 'time', 'discord', 'document', 'mail', 'facebook', 'globe', 'star', 'instagram', 'calendar', 'cards', 'collection', 'dice', 'book', 'external-link', 'linkedin', 'location', 'larp-mask', 'messenger', 'sword', 'image', 'announcement', 'partner', 'pdf', 'pawn', 'download', 'review', 'slack', 'users', 'home', 'arrow-right', 'tag', 'twitch', 'event', 'youtube');
  ALTER TABLE "footer_social_items" ALTER COLUMN "icon_name" SET DATA TYPE "public"."enum_footer_social_items_icon_name" USING "icon_name"::"public"."enum_footer_social_items_icon_name";`)
}
