/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    events: Event;
    'event-cycles': EventCycle;
    categories: Category;
    tags: Tag;
    media: Media;
    'member-profile-images': MemberProfileImage;
    'member-profiles': MemberProfile;
    'document-files': DocumentFile;
    documents: Document;
    partners: Partner;
    'club-sections': ClubSection;
    users: User;
    roles: Role;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      relatedPages: 'pages';
      relatedPosts: 'posts';
      relatedEvents: 'events';
      relatedEventCycles: 'event-cycles';
    };
    tags: {
      relatedPages: 'pages';
      relatedPosts: 'posts';
      relatedEvents: 'events';
      relatedEventCycles: 'event-cycles';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-cycles': EventCyclesSelect<false> | EventCyclesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'member-profile-images': MemberProfileImagesSelect<false> | MemberProfileImagesSelect<true>;
    'member-profiles': MemberProfilesSelect<false> | MemberProfilesSelect<true>;
    'document-files': DocumentFilesSelect<false> | DocumentFilesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'club-sections': ClubSectionsSelect<false> | ClubSectionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'website-permissions': WebsitePermission;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'website-permissions': WebsitePermissionsSelect<false> | WebsitePermissionsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  parent?: (number | null) | Page;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  heroImage?: (number | null) | Media;
  /**
   * Opcjonalny opis karty. Bez niego użyty zostanie początek pierwszego bloku treści.
   */
  listingExcerpt?: string | null;
  layout: (RichTextBlock | ListingBlock | MediaGalleryBlock | AttachmentsBlock | MemberProfilesBlock)[];
  seo?: {
    /**
     * Opcjonalny tytuł wyniku wyszukiwania. Domyślnie używany jest tytuł treści.
     */
    title?: string | null;
    description?: string | null;
    /**
     * Opcjonalny obraz dla udostępnień. Domyślnie używany jest obraz główny.
     */
    image?: (number | null) | Media;
  };
  /**
   * Adres jest tworzony automatycznie z tytułu, ale można go zmienić.
   */
  slug: string;
  author: number | User;
  /**
   * Ustawiana automatycznie przy pierwszej publikacji.
   */
  publishedAt?: string | null;
  systemKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Adres jest tworzony automatycznie z nazwy.
   */
  slug: string;
  description?: string | null;
  relatedPages?: {
    docs?: (number | Page)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  relatedPosts?: {
    docs?: (number | Post)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  relatedEvents?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  relatedEventCycles?: {
    docs?: (number | EventCycle)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Adres jest tworzony automatycznie z tytułu, ale można go zmienić.
   */
  slug: string;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  heroImage?: (number | null) | Media;
  /**
   * Krótkie wprowadzenie wyświetlane na listach wpisów.
   */
  excerpt: string;
  relatedEvents?: (number | Event)[] | null;
  relatedEventCycles?: (number | EventCycle)[] | null;
  layout: (RichTextBlock | ListingBlock | MediaGalleryBlock | AttachmentsBlock | MemberProfilesBlock)[];
  author: number | User;
  /**
   * Ustawiana automatycznie przy pierwszej publikacji.
   */
  publishedAt?: string | null;
  seo?: {
    /**
     * Opcjonalny tytuł wyniku wyszukiwania. Domyślnie używany jest tytuł treści.
     */
    title?: string | null;
    description?: string | null;
    /**
     * Opcjonalny obraz dla udostępnień. Domyślnie używany jest obraz główny.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Adres jest tworzony automatycznie z nazwy.
   */
  slug: string;
  description?: string | null;
  relatedPages?: {
    docs?: (number | Page)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  relatedPosts?: {
    docs?: (number | Post)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  relatedEvents?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  relatedEventCycles?: {
    docs?: (number | EventCycle)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  cycle?: (number | null) | EventCycle;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  heroImage?: (number | null) | Media;
  tagline?: string | null;
  excerpt: string;
  layout: (RichTextBlock | ListingBlock | MediaGalleryBlock | AttachmentsBlock | MemberProfilesBlock)[];
  timeMode: 'timed' | 'allDay';
  eventStatus: 'scheduled' | 'cancelled' | 'postponed' | 'rescheduled';
  startAt: string;
  endAt?: string | null;
  location: {
    venueName?: string | null;
    venueWebsite?: string | null;
    streetAddress?: string | null;
    postalCode?: string | null;
    city?: string | null;
    /**
     * W Mapach Google wybierz „Udostępnij → Umieść mapę” i wklej skopiowany kod HTML.
     */
    mapEmbedURL?: string | null;
    country: string;
  };
  participation: 'public' | 'members';
  visibility: 'public' | 'members';
  capacityMode: 'unlimited' | 'exact' | 'approximate';
  capacity?: number | null;
  organizers?:
    | {
        profile: number | MemberProfile;
        role?: string | null;
        responsibilities?: string | null;
        contactFor?: string | null;
        showContactChannels?: boolean | null;
        id?: string | null;
      }[]
    | null;
  partners?:
    | {
        partner: number | Partner;
        roles: ('coOrganizer' | 'sponsor' | 'partner' | 'patron' | 'venueHost' | 'support')[];
        contribution?: string | null;
        id?: string | null;
      }[]
    | null;
  externalLinks?:
    | {
        label: string;
        targetType: 'page' | 'category' | 'tag' | 'event' | 'eventCycle' | 'partner' | 'custom';
        event?: (number | null) | Event;
        eventCycle?: (number | null) | EventCycle;
        partner?: (number | null) | Partner;
        page?: (number | null) | Page;
        category?: (number | null) | Category;
        tag?: (number | null) | Tag;
        customScheme?: ('https' | 'http' | 'mailto' | 'tel' | 'path' | 'anchor') | null;
        /**
         * Możesz wkleić pełny adres — schemat zostanie rozpoznany automatycznie.
         */
        customAddress?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Opcjonalny tytuł wyniku wyszukiwania. Domyślnie używany jest tytuł treści.
     */
    title?: string | null;
    description?: string | null;
    /**
     * Opcjonalny obraz dla udostępnień. Domyślnie używany jest obraz główny.
     */
    image?: (number | null) | Media;
  };
  /**
   * Adres jest tworzony automatycznie z tytułu, ale można go zmienić.
   */
  slug: string;
  author: number | User;
  /**
   * Ustawiana automatycznie przy pierwszej publikacji.
   */
  publishedAt?: string | null;
  defaultsAppliedCycle?: (number | null) | EventCycle;
  previousStartAt?: string | null;
  publishedStartAt?: string | null;
  calendarUID?: string | null;
  calendarRevision: number;
  calendarFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-cycles".
 */
export interface EventCycle {
  id: number;
  title: string;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  heroImage?: (number | null) | Media;
  tagline?: string | null;
  excerpt: string;
  layout: (RichTextBlock | ListingBlock | MediaGalleryBlock | AttachmentsBlock | MemberProfilesBlock)[];
  visibility: 'public' | 'members';
  seo?: {
    /**
     * Opcjonalny tytuł wyniku wyszukiwania. Domyślnie używany jest tytuł treści.
     */
    title?: string | null;
    description?: string | null;
    /**
     * Opcjonalny obraz dla udostępnień. Domyślnie używany jest obraz główny.
     */
    image?: (number | null) | Media;
  };
  eventDefaults: {
    title?: string | null;
    heroImage?: (number | null) | Media;
    tagline?: string | null;
    excerpt?: string | null;
    layout: (RichTextBlock | ListingBlock | MediaGalleryBlock | AttachmentsBlock | MemberProfilesBlock)[];
    categories?: (number | Category)[] | null;
    tags?: (number | Tag)[] | null;
    defaultTimeMode?: ('timed' | 'allDay') | null;
    /**
     * Format GG:MM, np. 18:00
     */
    defaultStartTime?: string | null;
    defaultDurationMinutes?: number | null;
    location: {
      venueName?: string | null;
      venueWebsite?: string | null;
      streetAddress?: string | null;
      postalCode?: string | null;
      city?: string | null;
      /**
       * W Mapach Google wybierz „Udostępnij → Umieść mapę” i wklej skopiowany kod HTML.
       */
      mapEmbedURL?: string | null;
      country: string;
    };
    participation: 'public' | 'members';
    visibility: 'public' | 'members';
    capacityMode: 'unlimited' | 'exact' | 'approximate';
    capacity?: number | null;
    organizers?:
      | {
          profile: number | MemberProfile;
          role?: string | null;
          responsibilities?: string | null;
          contactFor?: string | null;
          showContactChannels?: boolean | null;
          id?: string | null;
        }[]
      | null;
    partners?:
      | {
          partner: number | Partner;
          roles: ('coOrganizer' | 'sponsor' | 'partner' | 'patron' | 'venueHost' | 'support')[];
          contribution?: string | null;
          id?: string | null;
        }[]
      | null;
    externalLinks?:
      | {
          label: string;
          targetType: 'page' | 'category' | 'tag' | 'event' | 'eventCycle' | 'partner' | 'custom';
          event?: (number | null) | Event;
          eventCycle?: (number | null) | EventCycle;
          partner?: (number | null) | Partner;
          page?: (number | null) | Page;
          category?: (number | null) | Category;
          tag?: (number | null) | Tag;
          customScheme?: ('https' | 'http' | 'mailto' | 'tel' | 'path' | 'anchor') | null;
          /**
           * Możesz wkleić pełny adres — schemat zostanie rozpoznany automatycznie.
           */
          customAddress?: string | null;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Adres jest tworzony automatycznie z tytułu, ale można go zmienić.
   */
  slug: string;
  author: number | User;
  /**
   * Ustawiana automatycznie przy pierwszej publikacji.
   */
  publishedAt?: string | null;
  calendarFeedKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Krótki opis obrazu dla czytników ekranu i sytuacji, gdy plik nie może się wyświetlić.
   */
  alt: string;
  description?: string | null;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName: string;
  roles: (number | Role)[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  description?: string | null;
  key: string;
  isSystem?: boolean | null;
  /**
   * Uprawnienia wielu ról sumują się. Dwa ograniczenia zaznaczone dla jednej operacji obowiązują jednocześnie.
   */
  permissions?:
    | {
        resource:
          | 'users'
          | 'media'
          | 'member-profiles'
          | 'member-profile-images'
          | 'pages'
          | 'posts'
          | 'events'
          | 'event-cycles'
          | 'partners'
          | 'documents-resolution'
          | 'documents-statute'
          | 'documents-regulations'
          | 'documents-minutes'
          | 'documents-report'
          | 'documents-agreement'
          | 'documents-license'
          | 'documents-other'
          | 'document-files'
          | 'club-sections'
          | 'categories'
          | 'tags'
          | 'navigation'
          | 'site-settings';
        readAllowed?: boolean | null;
        readOwn?: boolean | null;
        readPublished?: boolean | null;
        canCreate?: boolean | null;
        updateAllowed?: boolean | null;
        updateOwn?: boolean | null;
        updatePublished?: boolean | null;
        deleteAllowed?: boolean | null;
        deleteOwn?: boolean | null;
        deletePublished?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListingBlock".
 */
export interface ListingBlock {
  heading?: string | null;
  sources: ('pages' | 'posts' | 'events' | 'event-cycles')[];
  parentPage?: (number | null) | Page;
  category?: (number | null) | Category;
  tag?: (number | null) | Tag;
  sort: 'newest' | 'oldest' | 'titleAscending' | 'titleDescending' | 'eventDateAscending';
  view: 'cards' | 'compact' | 'grid';
  eventTimeFilter?: ('all' | 'upcoming' | 'past') | null;
  eventCycle?: (number | null) | EventCycle;
  pageSize: number;
  pagination?: boolean | null;
  parentFilter: 'none' | 'current' | 'specific';
  emptyMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'listing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaGalleryBlock".
 */
export interface MediaGalleryBlock {
  heading?: string | null;
  selectionMode: 'manual' | 'filters';
  items?:
    | {
        media: number | Media;
        id?: string | null;
      }[]
    | null;
  category?: (number | null) | Category;
  tag?: (number | null) | Tag;
  sort?: ('newest' | 'oldest' | 'nameAscending' | 'nameDescending') | null;
  view: 'cards' | 'list' | 'grid';
  pageSize: number;
  pagination?: boolean | null;
  emptyMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AttachmentsBlock".
 */
export interface AttachmentsBlock {
  heading?: string | null;
  selectionMode: 'manual' | 'filters';
  items?:
    | {
        media: number | Media;
        id?: string | null;
      }[]
    | null;
  category?: (number | null) | Category;
  tag?: (number | null) | Tag;
  sort?: ('newest' | 'oldest' | 'nameAscending' | 'nameDescending') | null;
  view: 'cards' | 'list' | 'grid';
  pageSize: number;
  pagination?: boolean | null;
  emptyMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'attachments';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MemberProfilesBlock".
 */
export interface MemberProfilesBlock {
  heading?: string | null;
  entries: {
    profile: number | MemberProfile;
    /**
     * Opcjonalna funkcja w kontekście tej strony, np. „Prezes Zarządu”.
     */
    contextLabel?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'memberProfiles';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-profiles".
 */
export interface MemberProfile {
  id: number;
  owner: number | User;
  /**
   * Imię i nazwisko, ksywa albo obie formy — dokładnie tak, jak mają być widoczne publicznie.
   */
  publicName: string;
  about?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * JPEG, PNG, WebP lub AVIF, maksymalnie 5 MiB. Nowy plik zastępuje poprzedni.
   */
  photo?: (number | null) | MemberProfileImage;
  interests?: string | null;
  /**
   * Pole opcjonalne — wizytówka nie musi dotyczyć grania.
   */
  games?:
    | {
        title: string;
        plays?: boolean | null;
        runs?: boolean | null;
        id?: string | null;
      }[]
    | null;
  clubFunction?: string | null;
  clubActivities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contactTopics?: string | null;
  /**
   * Podane adresy będą dostępne publicznie bez logowania.
   */
  contactChannels?:
    | {
        type:
          | 'email'
          | 'facebook'
          | 'messenger'
          | 'discord'
          | 'instagram'
          | 'bluesky'
          | 'mastodon'
          | 'linkedin'
          | 'youtube'
          | 'twitch'
          | 'website'
          | 'other';
        /**
         * Dla e-maila podaj adres. Dla pozostałych kanałów podaj pełny link HTTPS.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  slug: string;
  moderatorHidden?: boolean | null;
  moderationReason?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-profile-images".
 */
export interface MemberProfileImage {
  id: number;
  owner: number | User;
  isPubliclyUsed?: boolean | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    profile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  heroImage?: (number | null) | Media;
  excerpt: string;
  website?: string | null;
  layout: (RichTextBlock | ListingBlock | MediaGalleryBlock | AttachmentsBlock | MemberProfilesBlock)[];
  seo?: {
    /**
     * Opcjonalny tytuł wyniku wyszukiwania. Domyślnie używany jest tytuł treści.
     */
    title?: string | null;
    description?: string | null;
    /**
     * Opcjonalny obraz dla udostępnień. Domyślnie używany jest obraz główny.
     */
    image?: (number | null) | Media;
  };
  /**
   * Adres jest tworzony automatycznie z nazwy, ale można go zmienić.
   */
  slug: string;
  author: number | User;
  /**
   * Ustawiana automatycznie przy pierwszej publikacji.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-files".
 */
export interface DocumentFile {
  id: number;
  /**
   * Czytelna nazwa wyświetlana przy odnośniku do pliku.
   */
  label: string;
  document?: (number | null) | Document;
  uploadedBy?: (number | null) | User;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  /**
   * Adres jest tworzony automatycznie z tytułu, ale można go zmienić.
   */
  slug: string;
  documentType: 'resolution' | 'statute' | 'regulations' | 'minutes' | 'report' | 'agreement' | 'license' | 'other';
  /**
   * Na przykład 3/2026. Pole jest wymagane dla uchwał.
   */
  documentNumber?: string | null;
  documentDate: string;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  primaryFile: number | DocumentFile;
  attachments?: (number | DocumentFile)[] | null;
  author: number | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "club-sections".
 */
export interface ClubSection {
  id: number;
  name: string;
  backgroundImage?: (number | null) | Media;
  /**
   * Niższa liczba oznacza wcześniejszą pozycję.
   */
  displayOrder: number;
  destinationPage?: (number | null) | Page;
  menuItems?:
    | {
        label: string;
        targetType: 'page' | 'category' | 'tag' | 'event' | 'eventCycle' | 'partner' | 'custom';
        event?: (number | null) | Event;
        eventCycle?: (number | null) | EventCycle;
        partner?: (number | null) | Partner;
        page?: (number | null) | Page;
        category?: (number | null) | Category;
        tag?: (number | null) | Tag;
        customScheme?: ('https' | 'http' | 'mailto' | 'tel' | 'path' | 'anchor') | null;
        /**
         * Możesz wkleić pełny adres — schemat zostanie rozpoznany automatycznie.
         */
        customAddress?: string | null;
        openInNewTab?: boolean | null;
        iconSource?: ('system' | 'media') | null;
        systemIcon?:
          | (
              | 'time'
              | 'discord'
              | 'mail'
              | 'facebook'
              | 'star'
              | 'instagram'
              | 'calendar'
              | 'collection'
              | 'dice'
              | 'book'
              | 'location'
              | 'pawn'
              | 'review'
              | 'slack'
              | 'users'
            )
          | null;
        customIcon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Identyfikator techniczny tworzony automatycznie z nazwy.
   */
  slug: string;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-cycles';
        value: number | EventCycle;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'member-profile-images';
        value: number | MemberProfileImage;
      } | null)
    | ({
        relationTo: 'member-profiles';
        value: number | MemberProfile;
      } | null)
    | ({
        relationTo: 'document-files';
        value: number | DocumentFile;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'club-sections';
        value: number | ClubSection;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  categories?: T;
  tags?: T;
  heroImage?: T;
  listingExcerpt?: T;
  layout?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        listing?: T | ListingBlockSelect<T>;
        mediaGallery?: T | MediaGalleryBlockSelect<T>;
        attachments?: T | AttachmentsBlockSelect<T>;
        memberProfiles?: T | MemberProfilesBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  author?: T;
  publishedAt?: T;
  systemKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListingBlock_select".
 */
export interface ListingBlockSelect<T extends boolean = true> {
  heading?: T;
  sources?: T;
  parentPage?: T;
  category?: T;
  tag?: T;
  sort?: T;
  view?: T;
  eventTimeFilter?: T;
  eventCycle?: T;
  pageSize?: T;
  pagination?: T;
  parentFilter?: T;
  emptyMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaGalleryBlock_select".
 */
export interface MediaGalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  selectionMode?: T;
  items?:
    | T
    | {
        media?: T;
        id?: T;
      };
  category?: T;
  tag?: T;
  sort?: T;
  view?: T;
  pageSize?: T;
  pagination?: T;
  emptyMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AttachmentsBlock_select".
 */
export interface AttachmentsBlockSelect<T extends boolean = true> {
  heading?: T;
  selectionMode?: T;
  items?:
    | T
    | {
        media?: T;
        id?: T;
      };
  category?: T;
  tag?: T;
  sort?: T;
  view?: T;
  pageSize?: T;
  pagination?: T;
  emptyMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MemberProfilesBlock_select".
 */
export interface MemberProfilesBlockSelect<T extends boolean = true> {
  heading?: T;
  entries?:
    | T
    | {
        profile?: T;
        contextLabel?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  categories?: T;
  tags?: T;
  heroImage?: T;
  excerpt?: T;
  relatedEvents?: T;
  relatedEventCycles?: T;
  layout?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        listing?: T | ListingBlockSelect<T>;
        mediaGallery?: T | MediaGalleryBlockSelect<T>;
        attachments?: T | AttachmentsBlockSelect<T>;
        memberProfiles?: T | MemberProfilesBlockSelect<T>;
      };
  author?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  cycle?: T;
  categories?: T;
  tags?: T;
  heroImage?: T;
  tagline?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        listing?: T | ListingBlockSelect<T>;
        mediaGallery?: T | MediaGalleryBlockSelect<T>;
        attachments?: T | AttachmentsBlockSelect<T>;
        memberProfiles?: T | MemberProfilesBlockSelect<T>;
      };
  timeMode?: T;
  eventStatus?: T;
  startAt?: T;
  endAt?: T;
  location?:
    | T
    | {
        venueName?: T;
        venueWebsite?: T;
        streetAddress?: T;
        postalCode?: T;
        city?: T;
        mapEmbedURL?: T;
        country?: T;
      };
  participation?: T;
  visibility?: T;
  capacityMode?: T;
  capacity?: T;
  organizers?:
    | T
    | {
        profile?: T;
        role?: T;
        responsibilities?: T;
        contactFor?: T;
        showContactChannels?: T;
        id?: T;
      };
  partners?:
    | T
    | {
        partner?: T;
        roles?: T;
        contribution?: T;
        id?: T;
      };
  externalLinks?:
    | T
    | {
        label?: T;
        targetType?: T;
        event?: T;
        eventCycle?: T;
        partner?: T;
        page?: T;
        category?: T;
        tag?: T;
        customScheme?: T;
        customAddress?: T;
        openInNewTab?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  author?: T;
  publishedAt?: T;
  defaultsAppliedCycle?: T;
  previousStartAt?: T;
  publishedStartAt?: T;
  calendarUID?: T;
  calendarRevision?: T;
  calendarFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-cycles_select".
 */
export interface EventCyclesSelect<T extends boolean = true> {
  title?: T;
  categories?: T;
  tags?: T;
  heroImage?: T;
  tagline?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        listing?: T | ListingBlockSelect<T>;
        mediaGallery?: T | MediaGalleryBlockSelect<T>;
        attachments?: T | AttachmentsBlockSelect<T>;
        memberProfiles?: T | MemberProfilesBlockSelect<T>;
      };
  visibility?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  eventDefaults?:
    | T
    | {
        title?: T;
        heroImage?: T;
        tagline?: T;
        excerpt?: T;
        layout?:
          | T
          | {
              richText?: T | RichTextBlockSelect<T>;
              listing?: T | ListingBlockSelect<T>;
              mediaGallery?: T | MediaGalleryBlockSelect<T>;
              attachments?: T | AttachmentsBlockSelect<T>;
              memberProfiles?: T | MemberProfilesBlockSelect<T>;
            };
        categories?: T;
        tags?: T;
        defaultTimeMode?: T;
        defaultStartTime?: T;
        defaultDurationMinutes?: T;
        location?:
          | T
          | {
              venueName?: T;
              venueWebsite?: T;
              streetAddress?: T;
              postalCode?: T;
              city?: T;
              mapEmbedURL?: T;
              country?: T;
            };
        participation?: T;
        visibility?: T;
        capacityMode?: T;
        capacity?: T;
        organizers?:
          | T
          | {
              profile?: T;
              role?: T;
              responsibilities?: T;
              contactFor?: T;
              showContactChannels?: T;
              id?: T;
            };
        partners?:
          | T
          | {
              partner?: T;
              roles?: T;
              contribution?: T;
              id?: T;
            };
        externalLinks?:
          | T
          | {
              label?: T;
              targetType?: T;
              event?: T;
              eventCycle?: T;
              partner?: T;
              page?: T;
              category?: T;
              tag?: T;
              customScheme?: T;
              customAddress?: T;
              openInNewTab?: T;
              id?: T;
            };
      };
  slug?: T;
  author?: T;
  publishedAt?: T;
  calendarFeedKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  relatedPages?: T;
  relatedPosts?: T;
  relatedEvents?: T;
  relatedEventCycles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  relatedPages?: T;
  relatedPosts?: T;
  relatedEvents?: T;
  relatedEventCycles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  description?: T;
  categories?: T;
  tags?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-profile-images_select".
 */
export interface MemberProfileImagesSelect<T extends boolean = true> {
  owner?: T;
  isPubliclyUsed?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        profile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-profiles_select".
 */
export interface MemberProfilesSelect<T extends boolean = true> {
  owner?: T;
  publicName?: T;
  about?: T;
  photo?: T;
  interests?: T;
  games?:
    | T
    | {
        title?: T;
        plays?: T;
        runs?: T;
        id?: T;
      };
  clubFunction?: T;
  clubActivities?: T;
  contactTopics?: T;
  contactChannels?:
    | T
    | {
        type?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  moderatorHidden?: T;
  moderationReason?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-files_select".
 */
export interface DocumentFilesSelect<T extends boolean = true> {
  label?: T;
  document?: T;
  uploadedBy?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  documentType?: T;
  documentNumber?: T;
  documentDate?: T;
  summary?: T;
  content?: T;
  primaryFile?: T;
  attachments?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  heroImage?: T;
  excerpt?: T;
  website?: T;
  layout?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        listing?: T | ListingBlockSelect<T>;
        mediaGallery?: T | MediaGalleryBlockSelect<T>;
        attachments?: T | AttachmentsBlockSelect<T>;
        memberProfiles?: T | MemberProfilesBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "club-sections_select".
 */
export interface ClubSectionsSelect<T extends boolean = true> {
  name?: T;
  backgroundImage?: T;
  displayOrder?: T;
  destinationPage?: T;
  menuItems?:
    | T
    | {
        label?: T;
        targetType?: T;
        event?: T;
        eventCycle?: T;
        partner?: T;
        page?: T;
        category?: T;
        tag?: T;
        customScheme?: T;
        customAddress?: T;
        openInNewTab?: T;
        iconSource?: T;
        systemIcon?: T;
        customIcon?: T;
        id?: T;
      };
  slug?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  key?: T;
  isSystem?: T;
  permissions?:
    | T
    | {
        resource?: T;
        readAllowed?: T;
        readOwn?: T;
        readPublished?: T;
        canCreate?: T;
        updateAllowed?: T;
        updateOwn?: T;
        updatePublished?: T;
        deleteAllowed?: T;
        deleteOwn?: T;
        deletePublished?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  contactEmail?: string | null;
  heroImage?: (number | null) | Media;
  homepageEventWindowWeeks?: number | null;
  homepageEventSlideLimit?: number | null;
  homepagePostCount?: ('2' | '5' | '8') | null;
  copyrightText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerItems?:
    | {
        appearance: 'link' | 'icon' | 'button';
        label: string;
        targetType: 'page' | 'category' | 'tag' | 'event' | 'eventCycle' | 'partner' | 'custom';
        event?: (number | null) | Event;
        eventCycle?: (number | null) | EventCycle;
        partner?: (number | null) | Partner;
        page?: (number | null) | Page;
        category?: (number | null) | Category;
        tag?: (number | null) | Tag;
        customScheme?: ('https' | 'http' | 'mailto' | 'tel' | 'path' | 'anchor') | null;
        /**
         * Możesz wkleić pełny adres — schemat zostanie rozpoznany automatycznie.
         */
        customAddress?: string | null;
        openInNewTab?: boolean | null;
        iconSource?: ('system' | 'media') | null;
        systemIcon?:
          | (
              | 'time'
              | 'discord'
              | 'mail'
              | 'facebook'
              | 'star'
              | 'instagram'
              | 'calendar'
              | 'collection'
              | 'dice'
              | 'book'
              | 'location'
              | 'pawn'
              | 'review'
              | 'slack'
              | 'users'
            )
          | null;
        customIcon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  heroItems?:
    | {
        label: string;
        targetType: 'page' | 'category' | 'tag' | 'event' | 'eventCycle' | 'partner' | 'custom';
        event?: (number | null) | Event;
        eventCycle?: (number | null) | EventCycle;
        partner?: (number | null) | Partner;
        page?: (number | null) | Page;
        category?: (number | null) | Category;
        tag?: (number | null) | Tag;
        customScheme?: ('https' | 'http' | 'mailto' | 'tel' | 'path' | 'anchor') | null;
        /**
         * Możesz wkleić pełny adres — schemat zostanie rozpoznany automatycznie.
         */
        customAddress?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  socialItems?:
    | {
        label: string;
        targetType: 'page' | 'category' | 'tag' | 'event' | 'eventCycle' | 'partner' | 'custom';
        event?: (number | null) | Event;
        eventCycle?: (number | null) | EventCycle;
        partner?: (number | null) | Partner;
        page?: (number | null) | Page;
        category?: (number | null) | Category;
        tag?: (number | null) | Tag;
        customScheme?: ('https' | 'http' | 'mailto' | 'tel' | 'path' | 'anchor') | null;
        /**
         * Możesz wkleić pełny adres — schemat zostanie rozpoznany automatycznie.
         */
        customAddress?: string | null;
        openInNewTab?: boolean | null;
        iconSource?: ('system' | 'media') | null;
        systemIcon?:
          | (
              | 'time'
              | 'discord'
              | 'mail'
              | 'facebook'
              | 'star'
              | 'instagram'
              | 'calendar'
              | 'collection'
              | 'dice'
              | 'book'
              | 'location'
              | 'pawn'
              | 'review'
              | 'slack'
              | 'users'
            )
          | null;
        customIcon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        items?:
          | {
              label: string;
              targetType: 'page' | 'category' | 'tag' | 'event' | 'eventCycle' | 'partner' | 'custom';
              event?: (number | null) | Event;
              eventCycle?: (number | null) | EventCycle;
              partner?: (number | null) | Partner;
              page?: (number | null) | Page;
              category?: (number | null) | Category;
              tag?: (number | null) | Tag;
              customScheme?: ('https' | 'http' | 'mailto' | 'tel' | 'path' | 'anchor') | null;
              /**
               * Możesz wkleić pełny adres — schemat zostanie rozpoznany automatycznie.
               */
              customAddress?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-permissions".
 */
export interface WebsitePermission {
  id: number;
  /**
   * Dostęp anonimowy obowiązuje również po zalogowaniu. Role z prawem Odczytu w CMS automatycznie widzą opublikowane treści na WWW.
   */
  permissions?:
    | {
        resource:
          | 'media'
          | 'pages'
          | 'posts'
          | 'events'
          | 'event-cycles'
          | 'partners'
          | 'documents-resolution'
          | 'documents-statute'
          | 'documents-regulations'
          | 'documents-minutes'
          | 'documents-report'
          | 'documents-agreement'
          | 'documents-license'
          | 'documents-other'
          | 'club-sections';
        anonymousAllowed?: boolean | null;
        roles?: (number | Role)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactEmail?: T;
  heroImage?: T;
  homepageEventWindowWeeks?: T;
  homepageEventSlideLimit?: T;
  homepagePostCount?: T;
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerItems?:
    | T
    | {
        appearance?: T;
        label?: T;
        targetType?: T;
        event?: T;
        eventCycle?: T;
        partner?: T;
        page?: T;
        category?: T;
        tag?: T;
        customScheme?: T;
        customAddress?: T;
        openInNewTab?: T;
        iconSource?: T;
        systemIcon?: T;
        customIcon?: T;
        id?: T;
      };
  heroItems?:
    | T
    | {
        label?: T;
        targetType?: T;
        event?: T;
        eventCycle?: T;
        partner?: T;
        page?: T;
        category?: T;
        tag?: T;
        customScheme?: T;
        customAddress?: T;
        openInNewTab?: T;
        id?: T;
      };
  socialItems?:
    | T
    | {
        label?: T;
        targetType?: T;
        event?: T;
        eventCycle?: T;
        partner?: T;
        page?: T;
        category?: T;
        tag?: T;
        customScheme?: T;
        customAddress?: T;
        openInNewTab?: T;
        iconSource?: T;
        systemIcon?: T;
        customIcon?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              targetType?: T;
              event?: T;
              eventCycle?: T;
              partner?: T;
              page?: T;
              category?: T;
              tag?: T;
              customScheme?: T;
              customAddress?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-permissions_select".
 */
export interface WebsitePermissionsSelect<T extends boolean = true> {
  permissions?:
    | T
    | {
        resource?: T;
        anonymousAllowed?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}